name: Lint

on:
  pull_request:
    types: [ labeled ]

jobs:
  lint:
    if: ${{ github.event.label.name == 'lint' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/ruff-action@v3